### ISSUE TITLE
Ajout docker compose base de données local

### ISSUE THREAD

**Issue by osscoco** [osscoco/MusicMarketSpaceAngularDotnet#2]
- [ ] Créer l'architecture de dossier suivante : 

./docker/docker-compose.yml

- [ ] Editer ce fichier avec le contenu suivant : 

```
version: '3.9'

services:
  db:
    image: mysql:8.3.0

    ports:
      - '3306:3306'

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    
    env_file:
      - .env

    ports:
      - '8080:80'

    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'


volumes:
  db-data:
```

- [ ] Créer l'architecture de dossier suivante : 

./docker/.env

- [ ] Editer ce fichier avec le contenu suivant : 

```
MYSQL_ROOT_PASSWORD=ToUpDaTePaSsWoRd
MYSQL_DATABASE=ToUpDaTeDaTaBaSe
MYSQL_USER=ToUpDaTeUsEr
MYSQL_PASSWORD=ToUpDaTePaSsWoRd
```

- [ ] Créer l'architecture de dossier suivante : 

./.gitignore

- [ ] Editer ce fichier avec le contenu suivant : 

```
# Fichier de variables .env pour la connexion à la base de données via Docker  
docker/.env
```
